[package]
name = "sunflower"
version = "0.1.0"
authors = ["dujiajiyi"]

[lib]
name = "sunflower"

[dependencies]
mio = "0.6.12"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"
num_cpus = "1.7"
httparse = "1.2.4"
chrono = "0.4.0"
url = "1.6.0"